- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    work_dir: /Users/otokunaga/work
    repos_dir: "{{ work_dir}}/fonts"
    branch: master
    homebrew_cask_packages:
      - { name: adobe-reader }
      - { name: alfred  }
      - { name: java }
      - { name: skype }
      - { name: slack }
      - { name: webstorm }
      - { name: intellij-idea }
      - { name: vagrant }
      - { name: virtualbox }
    homebrew_packages:
      - { name: go }
      - { name: direnv }
      - { name: ag }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      - { name: fish }
      - { name: postgresql }

  tasks:
    - name: test brew install
      homebrew: name=peco state=installed
    - name: test brew install
      homebrew: name=peco state=installed
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
      # rictydiminishedを特定のディレクトリに移動
    - git: repo=https://github.com/yascentur/RictyDiminished.git dest={{ repos_dir }} version={{ branch }} 
    - name: フォントファイルをコピー
      shell: cp -f {{repos_dir}}/Ricty*.ttf ~/Library/Fonts/
      notify: run fc-cache
     # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
